FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -y && apt-get install -y curl python3-pip screen git
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN pip install git+https://github.com/huggingface/transformers.git@main accelerate
RUN pip3 install "fschat[model_worker,webui]"
# This is the dockerfile for: xingyaoww/vllm:v1.1.1
